services:
  cudl-search-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cudl-search-api
    environment:
      SOLR_HOST: ${SOLR_HOST:-host.docker.internal}
      SOLR_PORT: ${SOLR_PORT:-8983}
      API_PORT: ${API_PORT:-80}
    ports:
      - ${API_PORT}:${API_PORT}
